// GameConfig.js


// @later do multiple files
const gameHash = window.location.hash.slice(1);
const game = gameHash;

const levelUpRequirements = [
	{ level: 2, experience: 100 },
	{ level: 3, experience: 300 },
	{ level: 4, experience: 600 },
	{ level: 5, experience: 1000 },
	{ level: 6, experience: 1500 },
	{ level: 7, experience: 2100 },
	{ level: 8, experience: 2800 },
	{ level: 9, experience: 3600 },
	{ level: 10, experience: 4500 },
	{ level: 11, experience: 5500 },
	{ level: 12, experience: 6600 },
	{ level: 13, experience: 7800 },
	{ level: 14, experience: 9100 },
	{ level: 15, experience: 10500 },
	{ level: 16, experience: 12000 },
	{ level: 17, experience: 13600 },
	{ level: 18, experience: 15300 },
	{ level: 19, experience: 17100 },
	{ level: 20, experience: 19000 },
	{ level: 21, experience: 21000 },
	{ level: 22, experience: 23100 },
	{ level: 23, experience: 25300 },
	{ level: 24, experience: 27600 },
	{ level: 25, experience: 30000 },
	{ level: 26, experience: 32500 },
	{ level: 27, experience: 35100 },
	{ level: 28, experience: 37800 },
	{ level: 29, experience: 40600 },
	{ level: 30, experience: 43500 },
	{ level: 31, experience: 46500 },
	{ level: 32, experience: 49600 },
	{ level: 33, experience: 52800 },
	{ level: 34, experience: 56100 },
	{ level: 35, experience: 59500 },
	{ level: 36, experience: 63000 },
	{ level: 37, experience: 66600 },
	{ level: 38, experience: 70300 },
	{ level: 39, experience: 74100 },
	{ level: 40, experience: 78000 },
	{ level: 41, experience: 82000 },
	{ level: 42, experience: 86100 },
	{ level: 43, experience: 90300 },
	{ level: 44, experience: 94600 },
	{ level: 45, experience: 99000 },
	{ level: 46, experience: 103500 },
	{ level: 47, experience: 108100 },
	{ level: 48, experience: 112800 },
	{ level: 49, experience: 117600 },
	{ level: 50, experience: 122500 },
	{ level: 51, experience: 127500 },
	{ level: 52, experience: 132600 },
	{ level: 53, experience: 137800 },
	{ level: 54, experience: 143100 },
	{ level: 55, experience: 148500 },
	{ level: 56, experience: 154000 },
	{ level: 57, experience: 159600 },
	{ level: 58, experience: 165300 },
	{ level: 59, experience: 171100 },
	{ level: 60, experience: 177000 },
	{ level: 61, experience: 183000 },
	{ level: 62, experience: 189100 },
	{ level: 63, experience: 195300 },
	{ level: 64, experience: 201600 },
	{ level: 65, experience: 208000 },
	{ level: 66, experience: 214500 },
	{ level: 67, experience: 221100 },
	{ level: 68, experience: 227800 },
	{ level: 69, experience: 234600 },
	{ level: 70, experience: 241500 },
	{ level: 71, experience: 248500 },
	{ level: 72, experience: 255600 },
	{ level: 73, experience: 262800 },
	{ level: 74, experience: 270100 },
	{ level: 75, experience: 277500 },
	{ level: 76, experience: 285000 },
	{ level: 77, experience: 292600 },
	{ level: 78, experience: 300300 },
	{ level: 79, experience: 308100 },
	{ level: 80, experience: 316000 },
	{ level: 81, experience: 324000 },
	{ level: 82, experience: 332100 },
	{ level: 83, experience: 340300 },
	{ level: 84, experience: 348600 },
	{ level: 85, experience: 357000 },
	{ level: 86, experience: 365500 },
	{ level: 87, experience: 374100 },
	{ level: 88, experience: 382800 },
	{ level: 89, experience: 391600 },
	{ level: 90, experience: 400500 },
	{ level: 91, experience: 409500 },
	{ level: 92, experience: 418600 },
	{ level: 93, experience: 427800 },
	{ level: 94, experience: 437100 },
	{ level: 95, experience: 446500 },
	{ level: 96, experience: 456000 },
	{ level: 97, experience: 465600 },
	{ level: 98, experience: 475300 },
	{ level: 99, experience: 485100 },
	{ level: 100, experience: 495000 }
];

const statNames = [
	"damage",
	"defense",
	"precision",
	"evasion",
	"critical",
	"resistance",
	"block",
	"penetration"
];

const config = {
	fantasyClickerBattles: {
		areas: [
			{
			  name: "Shimmering Meadows",
			  description: "Shimmering Meadows is a picturesque landscape filled with vibrant wildflowers and lush greenery. Crystal-clear streams meander through the meadows, reflecting the sunlight and creating a dazzling display. The air is fresh and fragrant, carrying the scent of blooming flowers. It is a serene and tranquil place, inviting adventurers to explore its natural beauty.",
			},
			{
			  name: "Whispering Forest",
			  description: "Whispering Forest is an enchanted realm dominated by towering ancient trees. The dense canopy casts a mesmerizing pattern of light and shadow on the forest floor. Soft whispers seem to emanate from the trees, creating an otherworldly ambiance. The air is cool and crisp, and the ground is covered in a carpet of moss and fallen leaves. It is a place of mystery and magic, where secrets are whispered among the ancient trees.",
			},
			{
			  name: "Crystal Caverns",
			  description: "Crystal Caverns is a subterranean wonderland adorned with shimmering crystals of various hues. The cavern walls glisten with an ethereal glow, creating a breathtaking sight. Stalactites and stalagmites form intricate formations, giving the cave an otherworldly appearance. The air is cool and tinged with a hint of mineral scent. It is a place where the beauty of the underground world unfolds, waiting to be discovered.",
			},
			{
			  name: "Crimson Citadel",
			  description: "Crimson Citadel stands tall amidst a rugged landscape, its imposing architecture evoking a sense of power and mystery. The citadel is adorned with intricate carvings and towering spires that reach for the sky. Fiery torches illuminate the halls, casting dancing shadows. The air is thick with an aura of danger and forbidden knowledge. It is a place of dark allure, where only the boldest dare to venture.",
			},
			{
			  name: "Stormy Peaks",
			  description: "Stormy Peaks is a realm of towering mountains and relentless storms. Jagged cliffs and rocky terrain create a treacherous landscape. Thunder rumbles through the peaks, accompanied by flashes of lightning that light up the dark sky. Winds howl fiercely, carrying a sense of raw power. It is a place where nature's fury reigns supreme, testing the resilience and bravery of those who dare to conquer it.",
			},
			{
			  name: "Lost Catacombs",
			  description: "Lost Catacombs lie hidden beneath the surface, a labyrinthine maze of ancient tunnels and forgotten chambers. Crumbling pillars and eerie statues line the passageways, exuding an aura of decay and mystery. Flickering torches cast long shadows, adding to the sense of foreboding. The air is thick with the scent of dampness and ancient secrets. It is a place where the past lingers, waiting to be unearthed.",
			},
			{
			  name: "Celestial Observatory",
			  description: "Celestial Observatory is a celestial haven perched atop a high peak. The observatory offers a panoramic view of the star-studded night sky, where constellations twinkle in their eternal dance. Telescopes and instruments stand ready to unravel the mysteries of the cosmos. The air is crisp and tinged with the scent of fresh air and anticipation. It is a place where the wonders of the universe unfold, inviting stargazers and dreamers.",
			},
			{
			  name: "Frozen Tundra",
			  description: "Frozen Tundra stretches as far as the eye can see, a frozen wasteland cloaked in eternal winter. Snow-covered plains and icy peaks dominate the landscape, glistening in the pale sunlight. Frosty winds whip through the tundra, biting at exposed skin. The air is filled with a sense of icy solitude and quietude. It is a place of harsh beauty, where survival is a constant battle against the elements.",
			},
			{
			  name: "Volcanic Depths",
			  description: "Volcanic Depths is a fiery abyss filled with molten rock and intense heat. Rivers of lava flow through the depths, casting an ominous glow on the jagged rock formations. Sulfurous fumes fill the air, creating an acrid and suffocating atmosphere. Tremors shake the ground, a constant reminder of the volatile nature of the place. It is a realm of searing danger and untamed power, where only the most fearless dare to tread.",
			},
			{
			  name: "Cursed Catacombs",
			  description: "Cursed Catacombs hold the remnants of a forgotten civilization, entwined with dark magic and cursed energies. Crumbling tombs and crypts line the underground passages, bearing eerie inscriptions and macabre symbols. Flickering candles barely illuminate the desolate corridors, shrouded in an eternal twilight. The air is heavy with a sense of ancient curses and restless spirits. It is a place where the line between life and death blurs, testing the resolve of intrepid explorers.",
			},
		],
		enemies: [
			// Shimmering Meadows
			{ name: "Warthog", level: 1, icon: "🐗", currentHP: 0 },
			{ name: "Shadowfox", level: 2, icon: "🦊", currentHP: 0 },
			{ name: "Direwolf", level: 3, icon: "🐺", currentHP: 0 },
			{ name: "Thorn Ent", level: 4, icon: "🌿", currentHP: 0 },
			{ name: "Griffin", level: 5, icon: "🦅", currentHP: 0 },
			{ name: "Dark Knight", level: 6, icon: "👹", currentHP: 0 },
			{ name: "Pixie Sorcerer", level: 7, icon: "🧚‍♂️", currentHP: 0 },
			{ name: "Enchanted Dryad", level: 8, icon: "🌺", currentHP: 0 },
			{ name: "Illusionist Wizard", level: 9, icon: "🧙‍♀️", currentHP: 0 },
			// { name: "Legendary Guardian", level: 10, ", icon: "🌟", currentHP: 0 },
			// Whispering Forest
			{ name: "Goblin Warrior", level: 11, icon: "🧟‍♂️", currentHP: 0 },
			{ name: "Wicked Witch", level: 12, icon: "🧙‍♀️", currentHP: 0 },
			{ name: "Treant", level: 13,icon: "🌳", currentHP: 0 },
			{ name: "Banshee", level: 14, icon: "👻", currentHP: 0 },
			{ name: "Chimera", level: 15, icon: "🐲", currentHP: 0 },
			{ name: "Enraged Bear", level: 16, icon: "🐻", currentHP: 0 },
			{ name: "Nightshade Assassin", level: 17, icon: "🗡️", currentHP: 0 },
			{ name: "Druid Shaman", level: 18, icon: "🌿🔮", currentHP: 0 },
			{ name: "Siren Temptress", level: 19, icon: "🧜‍♀️", currentHP: 0 },
			// { name: "Forest Guardian", level: 20,  (Guardian)", icon: "🌳🦉", currentHP: 0 },
			// Crystal Caverns
			{ name: "Cave Spider", level: 21, icon: "🕷️", currentHP: 0 },
			{ name: "Frost Elemental", level: 22, icon: "❄️🌀", currentHP: 0 },
			{ name: "Crystal Golem", level: 23, icon: "💎🗿", currentHP: 0 },
			{ name: "Shadow Stalker", level: 24, icon: "👤🌑", currentHP: 0 },
			{ name: "Crystal Mage", level: 25, icon: "💎🧙‍♂️", currentHP: 0 },
			{ name: "Ancient Wyrm", level: 26, icon: "🐉🌳", currentHP: 0 },
			{ name: "Spectral Knight", level: 27, icon: "👻⚔️", currentHP: 0 },
			{ name: "Ice Queen", level: 28, icon: "👸❄️", currentHP: 0 },
			{ name: "Frozen Colossus", level: 29, icon: "❄️🗿", currentHP: 0 },
			// { name: "Eternal Frost Dragon", level: 30, icon: "❄️🐉", currentHP: 0 },
			// Crimson Citadel
			{ name: "Hellfire Imp", level: 31, icon: "🔥👿", currentHP: 0 },
			{ name: "Infernal Knight", level: 32, icon: "🔥⚔️", currentHP: 0 },
			{ name: "Lava Elemental", level: 33, icon: "🌋🔥", currentHP: 0 },
			{ name: "Death's Shadow", level: 34, icon: "☠️🌑", currentHP: 0 },
			{ name: "Crimson Succubus", level: 35, icon: "🔥👿🧚‍♀️", currentHP: 0 },
			{ name: "Molten Golem", level: 36, icon: "🔥💥🗿", currentHP: 0 },
			{ name: "Cursed Necromancer", level: 37, icon: "🔥🧟‍♂️", currentHP: 0 },
			{ name: "Ashen Witch", level: 38, icon: "🔥🧙‍♀️", currentHP: 0 },
			{ name: "Raging Inferno", level: 39, icon: "🔥🌋", currentHP: 0 },
			// { name: "Lord of Flames", level: 40, icon: "🔥👹", currentHP: 0 },
			// Stormy Peaks
			{ name: "Rock Golem", level: 41, icon: "🗿⛰️", currentHP: 0 },
			{ name: "Thunderbird", level: 42, icon: "⚡️🐦", currentHP: 0 },
			{ name: "Storm Shaman", level: 43, icon: "⚡️🧙‍♂️", currentHP: 0 },
			{ name: "Mistral Drake", level: 44, icon: "🌬️🐉", currentHP: 0 },
			{ name: "Yeti", level: 45, icon: "🏔️🦧", currentHP: 0 },
			{ name: "Whirling Dervish", level: 46, icon: "🌪️🧔", currentHP: 0 },
			{ name: "Frost Giant", level: 47, icon: "🌬️🗿", currentHP: 0 },
			{ name: "Tornado Elemental", level: 48, icon: "🌪️🌬️", currentHP: 0 },
			{ name: "Storm Lord", level: 49, icon: "⚡️👑", currentHP: 0 },
			// { name: "Tempest Dragon", level: 50, icon: "⚡️🐉", currentHP: 0 },
			// Lost Catacombs
			{ name: "Skeletal Warrior", level: 51, icon: "💀⚔️", currentHP: 0 },
			{ name: "Cursed Mummy", level: 52, icon: "🔮🧟‍♂️", currentHP: 0 },
			{ name: "Ghostly Apparition", level: 53, icon: "👻💀", currentHP: 0 },
			{ name: "Serpentine Cultist", level: 54, icon: "🔮🐍", currentHP: 0 },
			{ name: "Crypt Lich", level: 55, icon: "💀🔮", currentHP: 0 },
			{ name: "Shade Assassin", level: 56, icon: "👤🔪", currentHP: 0 },
			{ name: "Ghoul Hound", level: 57, icon: "🐕💀", currentHP: 0 },
			{ name: "Spectral Sorcerer", level: 58, icon: "🔮🌑", currentHP: 0 },
			{ name: "Ancient Skeleton", level: 59, icon: "☠️💀", currentHP: 0 },
			// { name: "Undying Wraith", level: 60, icon: "👤🌑", currentHP: 0 },
			// Celestial Observatory
			{ name: "Starlight Sprite", level: 61, icon: "✨🧚", currentHP: 0 },
			{ name: "Astral Guardian", level: 62, icon: "⭐🦉", currentHP: 0 },
			{ name: "Lunar Priestess", level: 63, icon: "🌙👸", currentHP: 0 },
			{ name: "Solar Elemental", level: 64, icon: "☀️🔥", currentHP: 0 },
			{ name: "Nebula Sorcerer", level: 65, icon: "🌌🧙‍♂️", currentHP: 0 },
			{ name: "Stardust Dragon", level: 66, icon: "✨🐉", currentHP: 0 },
			{ name: "Cosmic Specter", level: 67, icon: "👤✨", currentHP: 0 },
			{ name: "Celestial Oracle", level: 68, icon: "⭐🔮", currentHP: 0 },
			{ name: "Aurora Valkyrie", level: 69, icon: "🌌⚔️", currentHP: 0 },
			// { name: "Ethereal Serpent", level: 70,  (Serpent)", icon: "🌙🐍", currentHP: 0 },
			// Frozen Tundra
			{ name: "Ice Elemental", level: 71, icon: "🌬️❄️", currentHP: 0 },
			{ name: "Frost Shaman", level: 72, icon: "❄️🧙‍♂️", currentHP: 0 },
			{ name: "Glacial Golem", level: 73, icon: "❄️💎🗿", currentHP: 0 },
			{ name: "Snow Siren", level: 74, icon: "❄️🧜‍♀️", currentHP: 0 },
			{ name: "Winter Wolf", level: 75, icon: "❄️🐺", currentHP: 0 },
			{ name: "Avalanche Yeti", level: 76, icon: "❄️🏔️🦧", currentHP: 0 },
			{ name: "Frozen Banshee", level: 77, icon: "❄️👻", currentHP: 0 },
			{ name: "Blizzard Mage", level: 78, icon: "❄️🧙‍♂️❄️", currentHP: 0 },
			{ name: "Arctic Drake", level: 79, icon: "❄️🐉", currentHP: 0 },
			// { name: "Glacier Guardian", level: 80,  (Guardian)", icon: "❄️🏔️🦉", currentHP: 0 },
			// Volcanic Depths
			{ name: "Magma Elemental", level: 81, icon: "🌋🔥", currentHP: 0 },
			{ name: "Lava Shaman", level: 82, icon: "🌋🧙‍♂️", currentHP: 0 },
			{ name: "Infernal Golem", level: 83,  icon: "🌋💎🗿", currentHP: 0 },
			{ name: "Fire Sprite", level: 84, icon: "🔥🧚", currentHP: 0 },
			{ name: "Volcanic Drake", level: 85, icon: "🌋🐉", currentHP: 0 },
			{ name: "Obsidian Knight", level: 86, icon: "🌋⚔️", currentHP: 0 },
			{ name: "Hellhound", level: 87, icon: "🌋🐕", currentHP: 0 },
			{ name: "Searing Sorcerer", level: 88, icon: "🌋🧙‍♂️", currentHP: 0 },
			{ name: "Inferno Demon", level: 89, icon: "🌋👹", currentHP: 0 },
			// { name: "Eruption Guardian", level: 90,  (Guardian)", icon: "🌋🏔️🦉", currentHP: 0 },
			// Cursed Catacombs
			{ name: "Ghoul", level: 91, icon: "☠️🧟‍♂️", currentHP: 0 },
			{ name: "Shadowcaster", level: 92, icon: "🌑🧙‍♂️", currentHP: 0 },
			{ name: "Spectral Assassin", level: 93, icon: "🌑🗡️", currentHP: 0 },
			{ name: "Cursed Wraith", level: 94, icon: "🌑👻", currentHP: 0 },
			{ name: "Necrotic Warlock", level: 95, icon: "🌑🔮🧙‍♂️", currentHP: 0 },
			{ name: "Bone Dragon", level: 96, icon: "☠️🐉", currentHP: 0 },
			{ name: "Dark Priest", level: 97, icon: "🌑⚔️🙏", currentHP: 0 },
			{ name: "Phantom Knight", level: 98, icon: "🌑⚔️👻", currentHP: 0 },
			{ name: "Deathbringer", level: 99, icon: "🌑👤⚔️", currentHP: 0 },
			// { name: "Eternal Lich", level: 100, icon: "🌑💀🔮", currentHP: 0 }
		],
		bosses: [
			// Shimmering Meadows
			{ name: "Young Dragon", level: 10, icon: "🐉", currentHP: 0 },
			// Whispering Forest
			{ name: "Malevolent Sorcerer", level: 20, icon: "👺", currentHP: 0 },
			// Crystal Caverns
			{ name: "Crystal Behemoth", level: 30, icon: "💎🐲", currentHP: 0 },
			// Crimson Citadel
			{ name: "Inferno Demon", level: 40, icon: "🔥👹", currentHP: 0 },
			// Stormy Peaks
			{ name: "Raging Thunderbird", level: 50, icon: "⚡️🐦", currentHP: 0 },
			// Lost Catacombs
			{ name: "Necrotic Lich", level: 60, icon: "💀🔮", currentHP: 0 },
			// Celestial Observatory
			{ name: "Stellar Archangel", level: 70, icon: "⭐👼", currentHP: 0 },
			// Area - Frozen Tundra
			{ name: "Glacial King", level: 80, icon: "❄️👑", currentHP: 0 },
			// Area - Volcanic Depths
			{ name: "Molten Dragon", level: 90, icon: "🔥🐉", currentHP: 0 },
			// Area - Cursed Catacombs
			{ name: "Soul Reaper", level: 100, icon: "🌑👤☠️", currentHP: 0 }
		],
		itemsList: [
			// Armor items
			{ name: "Leather Armor", type: "stat", stat: "defense", icon: "🥼", level: 5 },
			{ name: "Chainmail Armor", type: "stat", stat: "defense", icon: "🔗", level: 10 },
			{ name: "Scale Armor", type: "stat", stat: "defense", icon: "🐉", level: 15 },
			{ name: "Plate Armor", type: "stat", stat: "defense", icon: "💌", level: 20 },
			{ name: "Dragonhide Armor", type: "stat", stat: "defense", icon: "🐉", level: 25 },
			{ name: "Steel Armor", type: "stat", stat: "defense", icon: "⚙️", level: 30 },
			{ name: "Ironclad Armor", type: "stat", stat: "defense", icon: "🛡️", level: 35 },
			{ name: "Mithril Armor", type: "stat", stat: "defense", icon: "⛰️", level: 40 },
			{ name: "Elven Robes", type: "stat", stat: "defense", icon: "🧝", level: 45 },
			{ name: "Ancient Plate Armor", type: "stat", stat: "defense", icon: "🏰", level: 50 },
			{ name: "Celestial Vestments", type: "stat", stat: "defense", icon: "✨", level: 55 },
			{ name: "Shadow Vestments", type: "stat", stat: "defense", icon: "🌑", level: 60 },
			{ name: "Titanium Mail", type: "stat", stat: "defense", icon: "🦾", level: 65 },
			{ name: "Voidbane Plate", type: "stat", stat: "defense", icon: "🌌", level: 70 },
			{ name: "Radiant Armor", type: "stat", stat: "defense", icon: "☀️", level: 75 },
			{ name: "Crystal Guardian", type: "stat", stat: "defense", icon: "💎", level: 80 },
			{ name: "Stormforged Plate", type: "stat", stat: "defense", icon: "⚡", level: 85 },
			{ name: "Ethereal Shroud", type: "stat", stat: "defense", icon: "🌌", level: 90 },
			{ name: "Divine Raiment", type: "stat", stat: "defense", icon: "✨", level: 95 },
			{ name: "Infinity Armor", type: "stat", stat: "defense", icon: "♾️", level: 100 },
			// Weapon items
			{ name: "Knife", type: "stat", stat: "damage", icon: "🔪", level: 5 },
			{ name: "Dagger", type: "stat", stat: "damage", icon: "🗡️", level: 10 },
			{ name: "Rapier", type: "stat", stat: "damage", icon: "🤺", level: 15 },
			{ name: "Shortsword", type: "stat", stat: "damage", icon: "🗡️", level: 20 },
			{ name: "Scimitar", type: "stat", stat: "damage", icon: "🔱", level: 25 },
			{ name: "Katana", type: "stat", stat: "damage", icon: "🗡️", level: 30 },
			{ name: "Mace", type: "stat", stat: "damage", icon: "🔨", level: 35 },
			{ name: "Morningstar", type: "stat", stat: "damage", icon: "🌅", level: 40 },
			{ name: "Hammer", type: "stat", stat: "damage", icon: "🔨", level: 45 },
			{ name: "Battleaxe", type: "stat", stat: "damage", icon: "🪓", level: 50 },
			{ name: "Glaive", type: "stat", stat: "damage", icon: "🍁", level: 55 },
			{ name: "Spear", type: "stat", stat: "damage", icon: "🌿", level: 60 },
			{ name: "Warhammer", type: "stat", stat: "damage", icon: "🔨", level: 65 },
			{ name: "Claymore", type: "stat", stat: "damage", icon: "🗡️", level: 70 },
			{ name: "Flail", type: "stat", stat: "damage", icon: "🔗", level: 75 },
			{ name: "Whip", type: "stat", stat: "damage", icon: "👻", level: 80 },
			{ name: "Halberd", type: "stat", stat: "damage", icon: "🪓", level: 85 },
			{ name: "Runeblade", type: "stat", stat: "damage", icon: "⚔️", level: 90 },
			{ name: "Longsword", type: "stat", stat: "damage", icon: "🗡️", level: 95 },
			{ name: "Excalibur", type: "stat", stat: "damage", icon: "🗡️", level: 100 },
			// Soulstones items
			{ name: "Soulstone of Renewal", type: "stat", stat: "regeneration", icon: "🕰️", level: 25 },
			{ name: "Soulstone of Vitality", type: "stat", stat: "regeneration", icon: "⌛", level: 50 },
			{ name: "Soulstone of Resurgence", type: "stat", stat: "regeneration", icon: "⏳", level: 75 },
			{ name: "Soulstone of Awakening", type: "stat", stat: "regeneration", icon: "🌅", level: 100 },
			// Gloves items
			{ name: "Leather Gloves", type: "stat", stat: "precision", icon: "🧤", level: 10 },
			{ name: "Chainmail Gauntlets", type: "stat", stat: "precision", icon: "🧤", level: 20 },
			{ name: "Plated Gauntlets", type: "stat", stat: "precision", icon: "🧤", level: 30 },
			{ name: "Dragonhide Gloves", type: "stat", stat: "precision", icon: "🧤", level: 40 },
			{ name: "Shadowsteel Gauntlets", type: "stat", stat: "precision", icon: "🧤", level: 50 },
			{ name: "Stormforged Handguards", type: "stat", stat: "precision", icon: "🧤", level: 60 },
			{ name: "Arcane Gloves", type: "stat", stat: "precision", icon: "🧤", level: 70 },
			{ name: "Gloves of the Eternal Sentinel", type: "stat", stat: "precision", icon: "🧤", level: 80 },
			{ name: "Divine Touch Gauntlets", type: "stat", stat: "precision", icon: "🧤", level: 90 },
			{ name: "Legendary Gauntlets", type: "stat", stat: "precision", icon: "🧤", level: 100 },
			// Trinkets items
			{ name: "Simple Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 10 },
			{ name: "Ornate Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 20 },
			{ name: "Enchanted Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 30 },
			{ name: "Mystical Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 40 },
			{ name: "Glowing Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 50 },
			{ name: "Celestial Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 60 },
			{ name: "Whispering Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 70 },
			{ name: "Shadow Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 80 },
			{ name: "Ethereal Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 90 },
			{ name: "Mythical Trinket", type: "stat", stat: "evasion", icon: "🔮", level: 100 },
			// Ring items
			{ name: "Ring of Precision", type: "stat", stat: "critical", icon: "💍", level: 5 },
			{ name: "Ring of Blinding Strikes", type: "stat", stat: "critical", icon: "✨", level: 15 },
			{ name: "Ring of Deadly Precision", type: "stat", stat: "critical", icon: "🔪", level: 25 },
			{ name: "Ring of Devastation", type: "stat", stat: "critical", icon: "💥", level: 35 },
			{ name: "Ring of Execution", type: "stat", stat: "critical", icon: "🗡️", level: 45 },
			{ name: "Ring of Annihilation", type: "stat", stat: "critical", icon: "☠️", level: 55 },
			{ name: "Ring of Ruthless Strikes", type: "stat", stat: "critical", icon: "🔥", level: 65 },
			{ name: "Ring of Piercing Precision", type: "stat", stat: "critical", icon: "🎯", level: 75 },
			{ name: "Ring of Focused Fury", type: "stat", stat: "critical", icon: "⚔️", level: 85 },
			{ name: "Ring of Merciless Strikes", type: "stat", stat: "critical", icon: "🌪️", level: 95 },
			// Cloak items
			{ name: "Tattered Cape", type: "stat", stat: "resistance", icon: "🧣", level: 5 },
			{ name: "Patchwork Vest", type: "stat", stat: "resistance", icon: "🐾", level: 15 },
			{ name: "Old Cloak", type: "stat", stat: "resistance", icon: "🕵️‍♂️", level: 25 },
			{ name: "Worn Tabard", type: "stat", stat: "resistance", icon: "🛡️", level: 35 },
			{ name: "Rogue's Cape", type: "stat", stat: "resistance", icon: "🌑", level: 45 },
			{ name: "Embroidered Vest", type: "stat", stat: "resistance", icon: "🧵", level: 55 },
			{ name: "Mystic Cloak", type: "stat", stat: "resistance", icon: "🌌", level: 65 },
			{ name: "Knight's Tabard", type: "stat", stat: "resistance", icon: "🛡️", level: 75 },
			{ name: "Enchanted Cape", type: "stat", stat: "resistance", icon: "✨", level: 85 },
			{ name: "Royal Velvet Cloak", type: "stat", stat: "resistance", icon: "👑", level: 95 },
			// Necklace items
			{ name: "Necklace of Fortune", type: "stat", stat: "bonusLoot", icon: "🔮", level: 20 },
			{ name: "Necklace of Prosperity", type: "stat", stat: "bonusLoot", icon: "💰", level: 40 },
			{ name: "Necklace of Serendipity", type: "stat", stat: "bonusLoot", icon: "🍀", level: 60 },
			{ name: "Necklace of Abundance", type: "stat", stat: "bonusLoot", icon: "🌟", level: 80 },
			// Charm items
			{ name: "Charm of Wisdom", type: "stat", stat: "bonusExp", icon: "📚", level: 10 },
			{ name: "Charm of Enlightenment", type: "stat", stat: "bonusExp", icon: "🌟", level: 30 },
			{ name: "Charm of Insight", type: "stat", stat: "bonusExp", icon: "🔍", level: 50 },
			{ name: "Charm of Mastery", type: "stat", stat: "bonusExp", icon: "🎓", level: 70 },
			{ name: "Charm of Ascendancy", type: "stat", stat: "bonusExp", icon: "⚡", level: 90 },
			// Belt items // @todo implement
			{ name: "Leather Belt", type: "stat", stat: "bonusHP", icon: "⚕️", level: 7 },
			{ name: "Chain Belt", type: "stat", stat: "bonusHP", icon: "🏋️", level: 17 },
			{ name: "Plated Belt", type: "stat", stat: "bonusHP", icon: "🛡️", level: 27 },
			{ name: "Reinforced Belt", type: "stat", stat: "bonusHP", icon: "💪", level: 37 },
			{ name: "Studded Belt", type: "stat", stat: "bonusHP", icon: "🔋", level: 47 },
			{ name: "Warrior Belt", type: "stat", stat: "bonusHP", icon: "⏱️", level: 57 },
			{ name: "Guardian Belt", type: "stat", stat: "bonusHP", icon: "🔒", level: 67 },
			{ name: "Knight Belt", type: "stat", stat: "bonusHP", icon: "🌅", level: 77 },
			{ name: "Titan Belt", type: "stat", stat: "bonusHP", icon: "🗿", level: 87 },
			{ name: "Epic Belt", type: "stat", stat: "bonusHP", icon: "🌟", level: 97 },
			// Amulet items //@todo implement
			{ name: "Amulet of Fire", type: "stat", stat: "elementalDamage", icon: "🔥", level: 18 },
			{ name: "Amulet of Ice", type: "stat", stat: "elementalDamage", icon: "❄️", level: 38 },
			{ name: "Amulet of Lightning", type: "stat", stat: "elementalDamage", icon: "⚡", level: 58 },
			{ name: "Amulet of Earth", type: "stat", stat: "elementalDamage", icon: "🌿", level: 78 },
			{ name: "Amulet of Elements", type: "stat", stat: "elementalDamage", icon: "🌍", level: 98 },
			// Shield items // @todo implement
			{ name: "Buckler", type: "stat", stat: "block", icon: "🛡️", level: 9 },
			{ name: "Kite Shield", type: "stat", stat: "block", icon: "🔰", level: 19 },
			{ name: "Heater Shield", type: "stat", stat: "block", icon: "🔥", level: 29 },
			{ name: "Round Shield", type: "stat", stat: "block", icon: "🔵", level: 39 },
			{ name: "Tower Shield", type: "stat", stat: "block", icon: "⚔️", level: 49 },
			{ name: "Pavise Shield", type: "stat", stat: "block", icon: "🌿", level: 59 },
			{ name: "Scutum Shield", type: "stat", stat: "block", icon: "⚔️", level: 69 },
			{ name: "Aegis Shield", type: "stat", stat: "block", icon: "🔱", level: 79 },
			{ name: "Bulwark Shield", type: "stat", stat: "block", icon: "🛡️", level: 89 },
			{ name: "Colossus Shield", type: "stat", stat: "block", icon: "🗿", level: 99 },
		],
		peopleInNeed: [
			"The distressed villagers",
			"A desperate knight",
			"The royal court",
			"The ancient order of wizards",
			"The sacred priesthood",
			"The renowned guild of adventurers",
			"The mythical creatures of the forest",
			"The noble lords and ladies"
		],
		aidRequests: [
			"implore your assistance",
			"plead for your aid",
			"request your intervention",
			"seek your heroic deeds",
			"crave your valiant help",
			"beg for your brave intervention",
			"yearn for your courageous action",
			"solicit your gallant support"
		],
		enemyDescriptors: [
			"fearsome",
			"malevolent",
			"dreaded",
			"vicious",
			"sinister",
			"ferocious",
			"cursed",
			"diabolical"
		],
		groupPhrases: [
			"A horde of",
			"A pack of",
			"A swarm of",
			"A legion of",
			"A band of",
			"An army of",
			"A brood of",
			"A congregation of"
		],
		actionVerbs: [
			"plaguing",
			"terrorizing",
			"menacing",
			"invading",
			"assaulting",
			"wreaking havoc upon",
			"threatening",
			"laying waste to"
		],
		locations: [
			"the realm",
			"a distant village",
			"the enchanted forest",
			"the ancient ruins",
			"the treacherous mountains",
			"a forgotten crypt",
			"the mystical swamps",
			"the forsaken castle"
		],
		challengeVerbs: [
			"challenges",
			"defies",
			"dares",
			"provokes",
			"taunts"
		],
		randomEnemies: [
			{ name: "Swordmaster", icon: "🗡️🛡️" },
			{ name: "Dark Sorcerer", icon: "🧙‍♂️🔮" },
			{ name: "Shadowblade", icon: "🗡️🌑" },
			{ name: "Ice Enchantress", icon: "❄️🧙‍♀️" },
			{ name: "Forest Ranger", icon: "🌲🏹" },
			{ name: "Thunder Warlock", icon: "⚡🧙‍♂️" },
			{ name: "Arcane Witch", icon: "🌌🧙‍♀️" },
			{ name: "Storm Knight", icon: "⚡🛡️" },
			{ name: "Plague Doctor", icon: "🩺😷" },
			{ name: "Doombringer", icon: "☠️🗡️" },
			{ name: "Mystic Monk", icon: "🧘‍♂️🕉️" },
			{ name: "Frost Queen", icon: "🌨️👸" },
			{ name: "Flame Knight", icon: "🔥⚔️" },
			{ name: "Silent Assassin", icon: "🤫🔪" },
			{ name: "Elven Ranger", icon: "🏹🧝" },
			{ name: "Dwarven Guardian", icon: "⛏️🛡️" },
			{ name: "Human Knight", icon: "👨‍🌾⚔️" }
		],
		gatheringItems: [
			{ name: "Iron Ore", type: "gathering", level: 1, icon: "⛏️" },
			{ name: "Copper Ore", type: "gathering", level: 2, icon: "🔨" },
			{ name: "Silver Ore", type: "gathering", level: 3, icon: "⚪" },
			{ name: "Gold Ore", type: "gathering", level: 4, icon: "💰" },
			{ name: "Platinum Ore", type: "gathering", level: 5, icon: "⚜️" },
			{ name: "Mithril Ore", type: "gathering", level: 6, icon: "⚙️" },
			{ name: "Adamantium Ore", type: "gathering", level: 7, icon: "⚛️" },
			{ name: "Dragonstone Ore", type: "gathering", level: 8, icon: "🐉" },
			{ name: "Voidium Ore", type: "gathering", level: 9, icon: "🌑" },
			{ name: "Celestium Ore", type: "gathering", level: 10, icon: "✨" }
		]
	}
};

const configData = config[game];

const areas = configData.areas;
const enemies = configData.enemies;
const bosses = configData.bosses;
const itemsList = configData.itemsList;
const gatheringItems = configData.gatheringItems;
const peopleInNeed = configData.peopleInNeed;
const aidRequests = configData.aidRequests;
const enemyDescriptors = configData.enemyDescriptors;
const groupPhrases = configData.groupPhrases;
const actionVerbs = configData.actionVerbs;
const locations = configData.locations;
const challengeVerbs = configData.challengeVerbs;
const randomEnemies = configData.randomEnemies;

const gameConfig = {
	areas: areas,
	enemies: enemies,
	bosses: bosses,
	itemsList: itemsList,
	gatheringItems: gatheringItems,
	peopleInNeed: peopleInNeed,
	aidRequests: aidRequests,
	enemyDescriptors: enemyDescriptors,
	groupPhrases: groupPhrases,
	actionVerbs: actionVerbs,
	locations: locations,
	challengeVerbs: challengeVerbs,
	randomEnemies: randomEnemies,
	statNames: statNames,
	levelUpRequirements: levelUpRequirements
}

export default gameConfig;


/*
// Unused
lootItems: [
	// Weapon items
	{ name: "Staff of Tranquility", type: "stat", stat: "damage", icon: "🏮", level: 3 },
	{ name: "Shenlong's Staff", type: "stat", stat: "damage", icon: "🐲", level: 7 },
	{ name: "Sword of Shadows", type: "stat", stat: "damage", icon: "🌑", level: 13 },
	{ name: "Kasumi's Blade", type: "stat", stat: "damage", icon: "🌸", level: 17 },
	{ name: "Maul of Fury", type: "stat", stat: "damage", icon: "🔨", level: 23 },
	{ name: "Kabuto's Hammer", type: "stat", stat: "damage", icon: "⚒️", level: 27 },
	{ name: "Blade of Valor", type: "stat", stat: "damage", icon: "⚔️", level: 33 },
	{ name: "Tidebreaker", type: "stat", stat: "damage", icon: "🌊", level: 37 },
	{ name: "Viper's Fang", type: "stat", stat: "damage", icon: "🐍", level: 43 },
	{ name: "Starshard Bow", type: "stat", stat: "damage", icon: "🌠", level: 47 },
	{ name: "Eclipse Scythe", type: "stat", stat: "damage", icon: "🌑", level: 53 },
	{ name: "Thunderstrike Axe", type: "stat", stat: "damage", icon: "⚡", level: 57 },
	{ name: "Frostbite Dagger", type: "stat", stat: "damage", icon: "❄️", level: 63 },
	{ name: "Soulreaper Scythe", type: "stat", stat: "damage", icon: "☠️", level: 67 },
	{ name: "Phoenixfire Wand", type: "stat", stat: "damage", icon: "🔥", level: 73 },
	{ name: "Voidblade Katana", type: "stat", stat: "damage", icon: "🌌", level: 77 },
	{ name: "Doomhammer", type: "stat", stat: "damage", icon: "💀", level: 83 },
	{ name: "Divine Staff", type: "stat", stat: "damage", icon: "✨", level: 87 },
	{ name: "Excalibur", type: "stat", stat: "damage", icon: "⚔️", level: 93 },
	{ name: "Blade of Eternity", type: "stat", stat: "damage", icon: "♾️", level: 97 },
	{ name: "Scepter of the Ancients", type: "stat", stat: "damage", icon: "👑", level: 100 },
	// Armor items
	{ name: "Elven Robes", type: "stat", stat: "defense", icon: "🧝", level: 3 },
	{ name: "Phoenix Feather Armor", type: "stat", stat: "defense", icon: "🐦", level: 7 },
	{ name: "Dragon Scale Armor", type: "stat", stat: "defense", icon: "🐉", level: 13 },
	{ name: "Celestial Plate Armor", type: "stat", stat: "defense", icon: "✨", level: 17 },
	{ name: "Shadowguard Vestments", type: "stat", stat: "defense", icon: "👥", level: 23 },
	{ name: "Tiger Claw Armor", type: "stat", stat: "defense", icon: "🐯", level: 27 },
	{ name: "Voidweaver Garb", type: "stat", stat: "defense", icon: "🌑", level: 33 },
	{ name: "Stormsteel Armor", type: "stat", stat: "defense", icon: "⚡", level: 37 },
	{ name: "Obsidian Scalemail", type: "stat", stat: "defense", icon: "🌋", level: 43 },
	{ name: "Spiritwalker's Robes", type: "stat", stat: "defense", icon: "👻", level: 47 },
	{ name: "Lionheart Plate", type: "stat", stat: "defense", icon: "🦁", level: 53 },
	{ name: "Shadowbane Vestments", type: "stat", stat: "defense", icon: "🌑", level: 57 },
	{ name: "Phoenixfire Robes", type: "stat", stat: "defense", icon: "🔥", level: 63 },
	{ name: "Voidshroud Armor", type: "stat", stat: "defense", icon: "🌌", level: 67 },
	{ name: "Soulweave Vestments", type: "stat", stat: "defense", icon: "🌑", level: 73 },
	{ name: "Divine Aegis", type: "stat", stat: "defense", icon: "✨", level: 77 },
	{ name: "Crystal Guardian", type: "stat", stat: "defense", icon: "💎", level: 83 },
	{ name: "Titanium Fortress", type: "stat", stat: "defense", icon: "🗼", level: 87 },
	{ name: "Ethereal Shroud", type: "stat", stat: "defense", icon: "🌌", level: 93 },
	{ name: "Infinity Armor", type: "stat", stat: "defense", icon: "♾️", level: 97 },
	{ name: "Celestial Garb", type: "stat", stat: "defense", icon: "🌟", level: 100 }
],
*/